### ISSUE TITLE
Play.py errors

### ISSUE THREAD

**Issue by ghost** [dakaugu/hqtrivia#1]
Traceback (most recent call last):
  File "D:\Desktop\hqtrivia-master\play.py", line 112, in <module>
    feed(img)
  File "D:\Desktop\hqtrivia-master\play.py", line 83, in feed
    text = pytesseract.image_to_string(image)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>>

**Comment by ghost** [comment]
All requirements are installed

**Comment by dakaugu** [comment]
Don't forget to install tesseract ocr

https://github.com/tesseract-ocr/tesseract/wiki
