### ISSUE TITLE
play.py error 503

### ISSUE THREAD

**Issue by ghost** [dakaugu/hqtrivia#2]
C:\Users\julia\Desktop\play>python play.py
QUESTION IS: ee HQ  Which fashion magazine is also the French word for "she" or "her"
OPTIONS ARE:
 []
Analyzing...
Traceback (most recent call last):
  File "play.py", line 112, in <module>
    feed(img)
  File "play.py", line 90, in feed
    calculate_answer(question, answers)
  File "play.py", line 70, in calculate_answer
    ans_occ = [x + y for x, y in zip(ans_occ, query_once(quest, ans))]
  File "play.py", line 47, in query_once
    content = get_response(query)
  File "play.py", line 36, in get_response
    response = urllib.request.urlopen(req).read()
  File "C:\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python36-32\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Python36-32\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

can you help me with this error?

**Comment by dakaugu** [comment]
Looks, like tesseract didn't recognize any options (multiple choice answers) leaving answers variable empty. Make sure to run rec.py and figure out what portion of the screen you are grabbing and see if no information from the questions are cut.

**Comment by dakaugu** [comment]
fixed 
https://github.com/dakaugu/hqtrivia/commit/506864a600b4a6c51cbe7c82c7fcf6c1fb23d76c
